### ISSUE TITLE
Build Failed on 4.3

### ISSUE THREAD

**Issue by ghost** [Havoc-OS/android_vendor_qcom_opensource_power#1]
FAILED:
vendor/qcom/opensource/power/Android.mk: error: "android.hardware.power-service-qti (EXECUTABLES android-arm64) missing vendor.lineage.power-ndk_platform (SHARED_LIBRARIES android-arm64)"

**Comment by AafaaqAli** [comment]
I am having the same issue, Can you guide me how you was able to fix the issue ?

**Comment by Biao7** [comment]
I am having the same issue too,Can you guide me how you wa able to fix the issue?
